ALTER TABLE admins ADD COLUMN department VARCHAR(100) DEFAULT NULL;
ALTER TABLE admins ADD COLUMN job_title VARCHAR(100) DEFAULT NULL;
ALTER TABLE admins ADD COLUMN phone VARCHAR(20) DEFAULT NULL;
ALTER TABLE admins ADD COLUMN profile_picture LONGBLOB DEFAULT NULL;
